# Generated by Django 5.2.7 on 2025-10-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100, unique=True, verbose_name='Nombre del equipo')),
                ('ciudad', models.CharField(max_length=100)),
                ('historia', models.TextField(verbose_name='Historia')),
                ('ligas_ganadas', models.IntegerField(default=0, verbose_name='Ligas ganadas')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
