# Generated by Django 5.2.6 on 2025-10-09 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del goleador')),
                ('nacionalidad', models.CharField(max_length=100)),
                ('goles', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('vallas_invictas', models.IntegerField(default=0, verbose_name='Vallas invictas')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goleadores', to='liga.equipo')),
            ],
            options={
                'verbose_name_plural': 'Goleadores',
            },
        ),
    ]
