# Generated by Django 5.2.7 on 2025-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='latitud',
            field=models.FloatField(default=3.430133854126975),
        ),
        migrations.AddField(
            model_name='equipo',
            name='longitud',
            field=models.FloatField(default=-76.54094749615665),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre_estadio',
            field=models.CharField(default='Estadio Desconocido', max_length=100),
        ),
    ]
