# Generated by Django 5.2.7 on 2026-01-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0004_equipo_latitud_equipo_longitud_equipo_nombre_estadio'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/', verbose_name='Escudo del equipo'),
        ),
    ]
