# Generated by Django 5.2.6 on 2026-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0005_equipo_escudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='llave_posicion',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Llave y posición en los playoffs'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='rating_ia',
            field=models.IntegerField(default=70, verbose_name='Rating de IA'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.URLField(blank=True, max_length=350, null=True, verbose_name='URL Escudo del equipo'),
        ),
    ]
